Fix the issue of tf.range where tensor with a different dtype is passed
This fix tries to address the issue raised in 29867 where
the following raises error:
```
tf.range(tf.constant(102), dtype=tf.float32)
...
...
ValueError: Tensor conversion requested dtype float32 for Tensor with dtype int32: 'tf.Tensor(102, shape=(), dtype=int32)'
```

This is different from `tf.arange` where different types could be used:
```
np.arange(np.int(102), dtype=np.float32)
```

The issue is that in tf.range cast is only done when dtype is not passed explicitly.

This fix adds additional processing so that the above scenario is covered.

This fix fixes 29867.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>