Pass the tensor directly instead of in a tuple.
Otherwise, fails with the error:
ValueError: Please provide model inputs as a list or tuple of 2 or 3 elements: (input, target) or (input, target, sample_weights) Received tf.Tensor(
PiperOrigin-RevId: 277763289
Change-Id: I8fea783d1ce0be53d63c24bde9a6af897d91c7d2