tfdbg: cosmetic fix to MonitoredSession.__del__ AttributeError
Prevoiusly, calling "del" on a tf_debug-wrapped MonitoredSession causes a warning message like the following:
Exception AttributeError: "'MonitoredSession' object has no attribute '__del__'" in <bound method LocalCLIDebuggerWrapperSessionForTest.__del__ of <__main__.LocalCLIDebuggerWrapperSessionForTest object at 0x558c74f642d0>> ignored

As the message states, the AttributeError is ignored and doesn't cause failures.

This CL prevents this message by checking that the underlying _sess object has the __del__ method defined before calling it.

Fixes: #15105
PiperOrigin-RevId: 178272619