Revert "Don't include traceme.h for ROCM."
This reverts commit 22a97f1ef5a8b10c72ba1ec8b463f063c6e5f22d.

THe reverted commit attempts to fix the ROCm build, but fails to do so. It merely trades bazel dependency error for compile time errors like the following:

```
tensorflow/core/nccl/nccl_manager.cc: In member function 'void tensorflow::NcclManager::LoopKernelLaunches(tensorflow::NcclManager::NcclStream*)':
tensorflow/core/nccl/nccl_manager.cc:689:9: error: 'profiler' has not been declared
         profiler::TraceMe trace_me("ncclAllReduce");
         ^
tensorflow/core/nccl/nccl_manager.cc:718:9: error: 'profiler' has not been declared
         profiler::TraceMe trace_me("ncclBroadcast");
         ^
tensorflow/core/nccl/nccl_manager.cc:729:9: error: 'profiler' has not been declared
         profiler::TraceMe trace_me("ncclReduce");
         ^
...
```