Fix tf.signal.inverse_stft AttributeError in tf 2.0
This fix tries to address the issue raised in 28444 where
tf.signal.inverse_stft causes AttributeError with:
```
frame_length = 512
frame_step = 256
signal = tf.random.uniform(shape=(1000,))
x = tf.signal.stft(signal, frame_length, frame_step)
y = tf.signal.inverse_stft(x, frame_length, frame_step)

AttributeError: 'int' object has no attribute 'value'
```

The issue is that, in `inverse_stft`, `real_frames.shape[-1].value`
has been used to get the value of the dim -1 for shape.
However, the `real_frames.shape[-1].value` only works
in non-eager mode where shape gives list of `Dimension` (value works).
It does not work in eager mode (2.0) where shape gives list
of ints.

This fix replaces with `real_frames.shape.as_list()[-1]` which
should work in eager and non-eager mode.

This fix fixes 28444.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

Additional fix up for tf.signal.inverse_stft shape

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>